### ISSUE TITLE
Facing SyntaxError: Unexpected token  when I install and boot for the first time

### ISSUE THREAD

**Issue by hfc01512** [flowforge/flowforge-device-agent#53]
### Current Behavior

I was introduced to this software by an acquaintance and started using it.
I have stored the device file device.yml in place and when I try to start it, I get the following error message and cannot start it.
I would appreciate any advice on how to correct this.

-----------------------------

/usr/local/lib/node_modules/@flowforge/flowforge-device-agent/lib/agent.js:47
                info(`Snapshot: ${this.currentSnapshot?.id || 'none'}`)
                                                       ^

SyntaxError: Unexpected token .
    at Module._compile (internal/modules/cjs/loader.js:723:23)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/@flowforge/flowforge-device-agent/index.js:3:19)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
------------------------------
Thank you

### Environment

- FlowForge version: 
- Node.js version: v10.19.0
- npm version: 6.14.4
- Platform/OS: Ubuntu 20.04
- Browser: chrome

**Comment by knolleary** [comment]
Hi @hfc01512 

I can see you are using Node.js v10. The device agent requires Node.js 16 or later. You will need to update your version of node.js to use the agent.

**Comment by hfc01512** [comment]
Hell knolleary,
Thanks for the advice.
I have successfully activated the system.

**Comment by hardillb** [comment]
fixed by #55
